Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1304, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1020, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%run -i ../python/common.py
# setup for examples
setupExamples("inforep", "../src/Makefile ../src/empty256.s ../src/oneplusone.s ../src/inforep.gdb ../src/setup.gdb")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mrun[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m-i ../python/common.py[39m[38;5;124m'[39m)
[1;32m      2[0m [38;5;66;03m# setup for examples[39;00m
[0;32m----> 3[0m [43msetupExamples[49m([38;5;124m"[39m[38;5;124minforep[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m../src/Makefile ../src/empty256.s ../src/oneplusone.s ../src/inforep.gdb ../src/setup.gdb[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'setupExamples' is not defined
NameError: name 'setupExamples' is not defined

